<?php

namespace ElxDigital\Vista\Services;

use \ElxDigital\Vista\Vista;

class Realty extends Vista {

    private $filds;
    private $params;

    private function getFilds() {
        $this->filds = [
            'AnoConstrucao',
            'AptosAndar',
            'AptosEdificio',
            'AreaConstruida',
            'AreaPrivativa',
            'AreaTerreno',
            'AreaTotal',
            'AreaUtil',
            'Bairro',
            'BairroComercial',
            'BanheiroSocialQtd',
            'Bloco',
            'CampanhaImportacao',
            'Categoria',
            'CEP',
            'Chave',
            'ChaveNaAgencia',
            'Cidade',
            'ClasseDoImovel',
            'Complemento',
            'CorretorPrimeiroAge',
            'DataAtualizacao',
            'DataCadastro',
            'DataDisponibilizacao',
            'DataFimAutorizacao',
            'DataImportacao',
            'DataInicioAutorizacao',
            'DataPlaca',
            'DescricaoWeb',
            'DimensoesTerreno',
            'Dormitorios',
            'EdificioResidencial',
            'EEmpreendimento',
            'EmDestaque',
            'EmpOrulo',
            'Empreendimento',
            'Endereco',
            'Exclusivo',
            'ExclusivoCorretor',
            'ExibirComentarios',
            'ExibirNoSite',
            'Garagem',
            'GaragemCoberta',
            'GaragemNumeroBox',
            'GaragemTipo',
            'Imediacoes',
            'Incompleto',
            'InformacaoVenda',
            'InscricaoMunicipal',
            'Lancamento',
            'Limpeza',
            'LocacaoAnual',
            'LocacaoTemporada',
            'LojasEdificio',
            'Lote',
            'Matricula',
            'MesConstrucao',
            'Midia',
            'Numero',
            'Observacoes',
            'ObsLocacao',
            'ObsVenda',
            'Ocupacao',
            'OLXFinalidadesPublicadas',
            'Orientacao',
            'Orulo',
            'Pais',
            'Pavimentos',
            'PercentualComissao',
            'PorteEstrutural',
            'PosicaoAndar',
            'ProjetoArquitetonico',
            'Proposta',
            'PropostaLocacao',
            'Quadra',
            'Reajuste',
            'Referencia',
            'Reformado',
            'Regiao',
            'Setor',
            'Situacao',
            'Status',
            'Suites',
            'SummerSale',
            'SuperDestaqueWeb',
            'TemPlaca',
            'TipoEndereco',
            'TipoImovel',
            'TipoOferta',
            'TituloSite',
            'UF',
            'Vagas',
            'ValorACombinar',
            'ValorComissao',
            'ValorCondominio',
            'ValorDiaria',
            'ValorIptu',
            'ValorLimpeza',
            'ValorLivreProprietario',
            'ValorLocacao',
            'ValorMensalPadrao',
            'ValorVenda',
            'Venda',
            'Visita',
            'VisitaAcompanhada',
            'WebEscritoriosDestaque',
            'Zona',
            'CategoriaImovel',
            'CategoriaMestre',
            'CategoriaGrupo',
            'ImoCodigo',
            'Moeda',
            'ConverterMoeda',
            'MoedaIndice',
            'CodigoEmpresa',
            'CodigoEmp',
            'CodigoEmpreendimento',
            'CodigoCategoria',
            'CodigoMoeda',
            'CodigoProprietario',
            'Proprietario',
            'ProprietarioPesquisa',
            'FotoProprietario',
            'DataHoraAtualizacao',
            'VideoDestaque',
            'VideoDestaqueTipo',
            'FotoDestaque',
            'FotoDestaquePequena',
            'FotoDestaqueEmpreendimento',
            'FotoDestaqueEmpreendimentoPequena',
            'Latitude',
            'Longitude',
            'Agenciador',
            'CorretorNome',
            'CodigoCorretor',
            'AssuntoProntuario',
            'PendenteProntuario',
            'EstadoProntuario',
            'DataInicioProntuario',
            'DataProntuario',
            'CodigoAgencia',
            'TotalBanheiros',
            'Caracteristicas' => [
                'Aberturas',
                'AguaQuente',
                'AndarDoApto',
                'Andares',
                'AreaServico',
                'BanheiroAuxiliar',
                'Bar',
                'Calefacao',
                'Churrasqueira',
                'ChurrasqueiraCondominio',
                'CircuitoFechadoTV',
                'Closet',
                'CopaCozinha',
                'Cozinha',
                'CozinhaMontada',
                'Deposito',
                'Despensa',
                'EstadoConservacaoImovel',
                'EstarIntimo',
                'Gabinete',
                'Gradeado',
                'Hidromassagem',
                'HidroSuite',
                'HomeTheater',
                'Lareira',
                'Lavabo',
                'LivingAmbientes',
                'LivingHall',
                'Marquise',
                'Mezanino',
                'Mobiliado',
                'Patio',
                'Piscina',
                'PiscinaAquecida',
                'Piso',
                'PisoAreaIntima',
                'Porao',
                'Quintal',
                'Sacada',
                'SacadaComChurrasqueira',
                'Sala',
                'SalaEstar',
                'SalaJantar',
                'SemiMobiliado',
                'Sotao',
                'Split',
                'SuiteMaster',
                'Terraco',
                'TVCabo',
                'Varanda',
                'VistaPanoramica',
            ],
            'InfraEstrutura' => [
                'Acude',
                'ArCentral',
                'ConstrucaoAlvenaria',
                'ConstrucaoMista',
                'Deck',
                'Elevador',
                'Elevadores',
                'EspacoGourmet',
                'Estacionamento',
                'EstacionamentoVagas',
                'EstadoConservacaoEdificio',
                'Fachada',
                'GasCentral',
                'Gradil',
                'Guarita',
                'Iluminacao',
                'Jardim',
                'JardimInverno',
                'Lavanderia',
                'Leste',
                'Norte',
                'Oeste',
                'Pilotis',
                'PiscinaColetiva',
                'PistaCaminhada',
                'Playground',
                'PocoArtesiano',
                'Portaria24Hrs',
                'PorteiroEletronico',
                'QuadraEsportes',
                'Quiosque',
                'SalaConvecoes',
                'SalaFitness',
                'SalaoBrinquedo',
                'SalaoFestas',
                'SalasEdificio',
                'Sauna',
                'SegurancaPatrimonial',
                'Spa',
                'Sul',
                'TerracoColetivo',
                'Zelador',
            ],
            'codigo' => ['Codigo'],
            'Corretor' => [
                'CodigoAgencia',
                'CPF_CGC',
                'Email',
                'Nome',
                'Nascimento',
                'Nacionalidade',
                'CNH',
                'Datacadastro',
                'CNHExpedicao',
                'RG_Inscricao',
                'CNHVencimento',
                'Celular',
                'Endereco',
                'Bairro',
                'Cidade',
                'UF',
                'Agencia',
                'CEP',
                'Pais',
                'Fone',
                'Fax',
                'RGEmissor',
                'Observacoes',
                'Administrativo',
                'Agenciador',
                'Gerente',
                'Empresa',
                'Codigo',
                'Celular1',
                'Celular2',
                'Corretor',
                'Datasaida',
                'Equipe',
                'Grupoacesso',
                'Nomecompleto',
                'Ramal',
                'Sexo',
                'Exibirnosite',
                'RecebeClientesemTrocaautomática',
                'Inativo',
                'CRECI',
                'Estadocivil',
                'Grupoacesso2',
                'NumeroFilhos',
                'Diretor',
                'Horario',
                'Reunião',
                'Angariação',
                'Venda',
                'MetaValordeVendas',
                'MetadeCaptacoes',
                'Chat',
                'CategoriaRanking',
                'AtuacaoVenda',
                'AtuacaoLocacao',
                'Foto',
                'Tipo',
                'CodigoEquipe',
            ],
            'Agencia' => [
                'Bairro',
                'Celular',
                'Cep',
                'Cidade',
                'Cnpj',
                'Codigo',
                'CpfResponsavel',
                'DDD',
                'Email',
                'Empresa',
                'Endereco',
                'EnderecoComplemento',
                'EnderecoNumero',
                'Fone',
                'Fone2',
                'Agencia',
                'Nome',
                'Pais',
                'RazaoSocial',
                'Responsavel',
                'Rresponsavel',
                'Uf',
                'Site',
            ],
            'Foto' => [
                'Codigo',
                'ImagemCodigo',
                'Data',
                'Descricao',
                'Destaque',
                'ExibirNoSite',
                'ExibirSite',
                'Foto',
                'FotoOriginal',
                'FotoPequena',
                'Tipo',
                'Origem',
                'Ordem',
            ],
            'FotoEmpreendimento' => [
                'Codigo',
                'Ordem',
                'Data',
                'Descricao',
                'Destaque',
                'Foto',
                'FotoPequena',
                'Tipo',
                'ExibirNoSite',
            ],
            'Anexo' => [
                'Codigo',
                'CodigoAnexo',
                'Descricao',
                'Anexo',
                'Arquivo',
                'ExibirNoSite',
                'ExibirSite',
                'Data',
            ],
            'Video' => [
                'Codigo',
                'VideoCodigo',
                'Data',
                'Descricao',
                'DescricaoWeb',
                'Destaque',
                'ExibirNoSite',
                'ExibirSite',
                'Video',
                'Tipo',
            ]
        ];
        return $this->filds;
    }

    public function getListFields() {
        $this->setEndPoint('imoveis/listarcampos');

        $return = $this->get();

        return $return;
    }

    public function getPropertiesFull() {
        $this->setEndPoint('imoveis/listar');
        $this->setTerms('&showtotal=1&pesquisa=');
        $this->params['fields'] = $this->getFilds();

        if (!empty($this->getOrder())) {
            $this->params['order'] = $this->getOrder();
        }

        if (!empty($this->getPagination())) {
            $this->params['paginacao'] = $this->getPagination();
        }

        $this->setParams($this->params);
        $return = $this->get();

        return $return;
    }

    public function getPropertiesDays(int $days) {
        $this->setEndPoint('imoveis/listar');
        $this->setTerms('&showtotal=1&pesquisa=');
        $this->params['fields'] = $this->getFilds();

        if (!empty($this->getOrder())) {
            $this->params['order'] = $this->getOrder();
        }

        if (!empty($this->getPagination())) {
            $this->params['paginacao'] = $this->getPagination();
        }

        $lastDay = date('Y-m-d', strtotime('-' . $days . ' days'));
        $day = date('Y-m-d');
        $this->setFilter('DataAtualizacao', [$lastDay, $day]);
        
        $this->setParams($this->params);
        $return = $this->get();

        return $return;
    }

}
